version: '2'
services:
  common:
    image: python:3.6
    working_dir: /workdir
    environment:
      PYTHONUSERBASE: /workdir/.pip
      PYTHONDONTWRITEBYTECODE: 1
      PATH: "/workdir/.pip/bin/:/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin"
      HISTFILE: docker-compose/.bash_history
      AIRFLOW_HOME: /workdir/airflow
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgres+psycopg2://airflow:airflow@db/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW_GPL_UNIDECODE: 'yes'
    command: ./bin/setup
    volumes:
      - .:/workdir

  app:
    extends: common
    command: airflow webserver
    links:
      - db
    ports:
      - 8080:8080

  scheduler:
    extends: common
    links:
      - db
    command: airflow scheduler

  db:
    image: postgres:11
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - .:/workdir
